# Generated by Django 3.2.18 on 2023-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('duration', models.DurationField()),
                ('equipment', models.ManyToManyField(to='prescriptions.Equipment')),
                ('muscle_groups', models.ManyToManyField(to='prescriptions.MuscleGroup')),
            ],
        ),
    ]
