# Generated by Django 3.2.18 on 2023-03-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fri', models.ManyToManyField(related_name='fri', to='prescriptions.Workout')),
                ('mon', models.ManyToManyField(related_name='mon', to='prescriptions.Workout')),
                ('sat', models.ManyToManyField(related_name='sat', to='prescriptions.Workout')),
                ('sun', models.ManyToManyField(related_name='sun', to='prescriptions.Workout')),
                ('thu', models.ManyToManyField(related_name='thu', to='prescriptions.Workout')),
                ('tue', models.ManyToManyField(related_name='tue', to='prescriptions.Workout')),
                ('wed', models.ManyToManyField(related_name='wed', to='prescriptions.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('rep', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.workout')),
            ],
        ),
    ]
