# Generated by Django 3.2.18 on 2023-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_workoutprescription_workoutsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsheet',
            name='fri',
            field=models.ManyToManyField(blank=True, related_name='fri', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='mon',
            field=models.ManyToManyField(blank=True, related_name='mon', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='sat',
            field=models.ManyToManyField(blank=True, related_name='sat', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='sun',
            field=models.ManyToManyField(blank=True, related_name='sun', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='thu',
            field=models.ManyToManyField(blank=True, related_name='thu', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='tue',
            field=models.ManyToManyField(blank=True, related_name='tue', to='prescriptions.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutsheet',
            name='wed',
            field=models.ManyToManyField(blank=True, related_name='wed', to='prescriptions.Workout'),
        ),
    ]
