# Generated by Django 3.2.18 on 2023-05-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_auto_20230331_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='muscle_groups',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
