# Generated by Django 3.2.18 on 2023-05-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_auto_20230508_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsheet',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='workoutsheet',
            name='wed',
        ),
        migrations.DeleteModel(
            name='WorkoutPrescription',
        ),
    ]
