# Generated by Django 3.2.3 on 2023-05-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_workoutprescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Exercise',
        ),
    ]
