# Generated by Django 3.2.3 on 2023-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_auto_20230517_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutitem',
            old_name='workout',
            new_name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutitem',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='workoutitem',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='workoutitem',
            name='set',
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='reps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='sets',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
